# App cmake


# Make CMake see the just-installed package
#
#list(PREPEND CMAKE_PREFIX_PATH "${BLUEOPENCV_INSTALL_DIR}/sdk/native/jni")
#list(PREPEND CMAKE_PREFIX_PATH "${BLUEDATACHANNEL_INSTALL_DIR}")
#list(PREPEND CMAKE_PREFIX_PATH "${BLUEXR_INSTALL_DIR}/lib/cmake/openxr")

# Append deps to cmake prefix
list(PREPEND CMAKE_PREFIX_PATH ${BLUEXR_INSTALL_DIR})
list(PREPEND CMAKE_PREFIX_PATH ${BLUEOPENCV_INSTALL_DIR}/sdk/native/jni/abi-arm64-v8a)
list(PREPEND CMAKE_PREFIX_PATH ${BLUEDATACHANNEL_INSTALL_DIR})

message(AUTHOR_WARNING "CMAKE_PREFIX_PATH is: ${CMAKE_PREFIX_PATH}")

# inner project
ExternalProject_Add(app
        SOURCE_DIR "${CMAKE_SOURCE_DIR}/app"        # your real project
        BINARY_DIR "${CMAKE_BINARY_DIR}/app/build"
        INSTALL_DIR "${CMAKE_BINARY_DIR}/app/install"
        DEPENDS bluexr blueopencv bluedatachannel
        CMAKE_ARGS
        $<$<BOOL:${CMAKE_TOOLCHAIN_FILE}>:-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}>
        -DCMAKE_BUILD_TYPE=$<IF:$<CONFIG:>,$<CONFIG>,${CMAKE_BUILD_TYPE}>
        -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
        -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}
        -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
        -DCMAKE_CXX_STANDARD_REQUIRED=${CMAKE_CXX_STANDARD_REQUIRED}
        -DCMAKE_CXX_EXTENSIONS=${CMAKE_CXX_EXTENSIONS}
        -DCMAKE_C_STANDARD=${CMAKE_C_STANDARD}
        -DCMAKE_C_STANDARD_REQUIRED=${CMAKE_C_STANDARD_REQUIRED}
        -DCMAKE_EXPORT_COMPILE_COMMANDS=${CMAKE_EXPORT_COMPILE_COMMANDS}
        -DCMAKE_SYSTEM_NAME=${CMAKE_SYSTEM_NAME}
        -DANDROID_SDK_PATH=$ENV{ANDROID_SDK_PATH}
        -DANDROID_SDK_ROOT=$ENV{ANDROID_SDK_PATH}
        -DANDROID_STL=${ANDROID_STL}
        -DANDROID_PLATFORM=${ANDROID_PLATFORM}
        -DBUILD_TOOLS=${BUILD_TOOLS}
        -DANDROID_ABI=${ANDROID_ABI}
        -DCMAKE_OBJECT_PATH_MAX=${CMAKE_OBJECT_PATH_MAX}
        # Gradle Build
        -DGRADLE_BUILD=${GRADLE_BUILD}
        BUILD_COMMAND ${CMAKE_COMMAND} --build <BINARY_DIR> --config $<CONFIG>
        INSTALL_COMMAND "${CMAKE_COMMAND}" --build <BINARY_DIR> --target install
)
